version: 2.0
jobs:
  lint:
    docker:
      - image: cimg/go:1.23-node
    steps:
      - run: node --version
      - run: npm --version
      - checkout
      - restore_cache:
          keys:
            - npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-v1-{{ .Branch }}-
            - npm-packages-v1-master-
            - npm-packages-v1-
      - run: npm ci
      - run: npm run build
      - save_cache:
          paths:
            - ~/.npm
          key: npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run lint
  test-unit:
    docker:
      - image: cimg/go:1.23-node
    steps:
      - run: node --version
      - run: npm --version
      - checkout
      - restore_cache:
          keys:
            - npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-v1-{{ .Branch }}-
            - npm-packages-v1-master-
            - npm-packages-v1-
      - run: npm ci
      - run: npm run build
      - save_cache:
          paths:
            - ~/.npm
          key: npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run test:unit -- --reporter=verbose
  test-e2e:
    docker:
      - image: cimg/go:1.23-node
    steps:
      - run: node --version
      - run: npm --version
      - checkout
      - restore_cache:
          keys:
            - npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-v1-{{ .Branch }}-
            - npm-packages-v1-master-
            - npm-packages-v1-
      - run: npm ci
      - run: npm run build
      - save_cache:
          paths:
            - ~/.npm
          key: npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run test:e2e
  demo:
    docker:
      - image: cimg/go:1.23-node
    steps:
      - run: node --version
      - run: npm --version
      - checkout
      - restore_cache:
          keys:
            - npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-v1-{{ .Branch }}-
            - npm-packages-v1-master-
            - npm-packages-v1-
      - run: npm ci
      - run: npm run build
      - save_cache:
          paths:
            - ~/.npm
          key: npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run build:dataset -w sqip-demo
      - run: npm run build:html -w sqip-demo
      - store_artifacts:
          path: /home/circleci/project/demo/public
          destination: demo
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test-unit
      - test-e2e
      - demo
